# Generated by Django 4.1.6 on 2023-02-09 07:07

from django.db import migrations
from apps.blog.models import BlogCategory


def add_blog_categories(apps, schema_editor):
    categories = [
        'Новости',
        'Партнеры',
        'Обзоры',
        'Акции',
        'Специальные предложения',


    ]
    #синтаксис для работы баз данных, автоматически , name - так как одно поле в Blog in file models.py
    for category in categories:
        BlogCategory.objects.create(name=category)

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_tags'),
    ]

    operations = [
        #автоматизируем процесс миграции
        migrations.RunPython(add_blog_categories)
    ]
